src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity=SubCategory::class, inversedBy="Article")
     * @ORM\JoinColumn(nullable=false)
     */
    private $subCategories;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="text")
     */
    private $Content2;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Content3;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Content4;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Content5;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image4;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title4;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title5;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getSubCategories(): ?SubCategory
    {
        return $this->subCategories;
    }

    public function setSubCategories(?SubCategory $subCategories): self
    {
        $this->subCategories = $subCategories;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getContent2(): ?string
    {
        return $this->Content2;
    }

    public function setContent2(string $Content2): self
    {
        $this->Content2 = $Content2;

        return $this;
    }

    public function getContent3(): ?string
    {
        return $this->Content3;
    }

    public function setContent3(?string $Content3): self
    {
        $this->Content3 = $Content3;

        return $this;
    }

    public function getContent4(): ?string
    {
        return $this->Content4;
    }

    public function setContent4(?string $Content4): self
    {
        $this->Content4 = $Content4;

        return $this;
    }

    public function getContent5(): ?string
    {
        return $this->Content5;
    }

    public function setContent5(?string $Content5): self
    {
        $this->Content5 = $Content5;

        return $this;
    }

    public function getImage2(): ?string
    {
        return $this->image2;
    }

    public function setImage2(string $image2): self
    {
        $this->image2 = $image2;

        return $this;
    }

    public function getImage3(): ?string
    {
        return $this->image3;
    }

    public function setImage3(?string $image3): self
    {
        $this->image3 = $image3;

        return $this;
    }

    public function getImage4(): ?string
    {
        return $this->image4;
    }

    public function setImage4(?string $image4): self
    {
        $this->image4 = $image4;

        return $this;
    }

    public function getTitle2(): ?string
    {
        return $this->title2;
    }

    public function setTitle2(?string $title2): self
    {
        $this->title2 = $title2;

        return $this;
    }

    public function getTitle3(): ?string
    {
        return $this->title3;
    }

    public function setTitle3(?string $title3): self
    {
        $this->title3 = $title3;

        return $this;
    }

    public function getTitle4(): ?string
    {
        return $this->title4;
    }

    public function setTitle4(?string $title4): self
    {
        $this->title4 = $title4;

        return $this;
    }

    public function getTitle5(): ?string
    {
        return $this->title5;
    }

    public function setTitle5(?string $title5): self
    {
        $this->title5 = $title5;

        return $this;
    }
}

src/Entity/SubCategory.php
<?php

namespace App\Entity;

use App\Repository\SubCategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SubCategoryRepository::class)
 */
class SubCategory
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="subCategories")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Category;

    /**
     * @ORM\OneToMany(targetEntity=Article::class, mappedBy="subCategories", orphanRemoval=true)
     */
    private $Article;

    public function __construct()
    {
        $this->Article = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticle(): Collection
    {
        return $this->Article;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->Article->contains($article)) {
            $this->Article[] = $article;
            $article->setSubCategories($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->Article->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getSubCategories() === $this) {
                $article->setSubCategories(null);
            }
        }

        return $this;
    }
}

templates/accueil.html.twig
{% extends "base.html.twig" %}

{% block content %}

    <main>

        <div class="margin">
        
            <h2 class="center" id="h2">Accueil</h2>

            <button class="right" id="add_article"><a href="{{ path('article_create') }}">Ajouter un article</a></button>

        </div>

        <section class="center">
        {% for article in articles %}
            <article id="article">

                <h3 id="h3">{{ article.title }}</h3>

                <p id="onleft" class="p">{{ article.content }}</p>

                <img src="{{ asset('./assets/image/') ~ article.image }}" alt="">

                <br>

                <span class="span">Catégorie de l'article : {{ article.subcategories.category.name }}</span>

                <span class="span">Mot clé de recherche : {{ article.subcategories.name }}</span>

                <br>

                <div class="">

                    <button><a href="{{ path('article', {'id':article.id}) }}">Voir plus</a></button>

                    <button><a href="{{ path('article_delete', {'id':article.id}) }}">Supprimer l'article</a></button>

                    <button><a href="{{ path('article_update', {'id':article.id}) }}">Modifier l'article</a></button>

                </div>

            </article>
        {% endfor %}
        
        </section>

    </main>

{% endblock %}

templates/article.html.twig
{% extends "base.html.twig" %}

{% block content %}

    <main>

        <h2>{{ article.title }}</h2>

        <p>{{ article.content }}</p>

        <img src="{{ asset('assets/image') ~ article.image }}" alt="">

        <h3>{{ article.title2 }}</h3>

        <p>{{ article.content2 }}</p>

        <p>{{ article.content3 }}</p>

        <p>{{ article.date|date("m/d/y") }}</p>

        <button><a href="{{ path('accueil') }}">Retour à l'accueil</a></button>

    </main>

{% endblock %}

templates/article_create.html.twig
{% extends "base.html.twig" %}

{% block content %}

    <main>

        <h2>Création d'un article :</h2>

    {{ form_start(formulaire) }}

        <div>
        {{ form_label(formulaire.title,"Titre") }}
        {{ form_widget(formulaire.title) }}
        </div>

        <div>
        {{ form_label(formulaire.content,"Paragraphe 01") }}
        {{ form_widget(formulaire.content) }}
        </div>

        <div>
        {{ form_label(formulaire.image,"Image 01 (Optionnel)") }}
        {{ form_widget(formulaire.image) }}
        </div>

        <div>
        {{ form_label(formulaire.title2,"Second Titre (Optionnel)") }}
        {{ form_widget(formulaire.title2) }}
        </div>

        <div>
        {{ form_label(formulaire.Content2,"Paragraphe 02") }}
        {{ form_widget(formulaire.Content2) }}
        </div>

        <div>
        {{ form_label(formulaire.image2,"Image 02") }}
        {{ form_widget(formulaire.image2) }}
        </div>

        <div>
        {{ form_label(formulaire.title3,"Troisième Titre (Optionnel)") }}
        {{ form_widget(formulaire.title3) }}
        </div>

        <div>
        {{ form_label(formulaire.Content3,"Paragraphe 03 (Optionnel)") }}
        {{ form_widget(formulaire.Content3) }}
        </div>

        <div>
        {{ form_label(formulaire.image3,"Image 03 (Optionnel)") }}
        {{ form_widget(formulaire.image3) }}
        </div>

        <div>
        {{ form_label(formulaire.title4,"Quatrième Titre (Optionnel)") }}
        {{ form_widget(formulaire.title4) }}
        </div>

        <div>
        {{ form_label(formulaire.Content4,"Paragraphe 04 (Optionnel)") }}
        {{ form_widget(formulaire.Content4) }}
        </div>

        <div>
        {{ form_label(formulaire.image4,"Image 04 (Optionnel)") }}
        {{ form_widget(formulaire.image4) }}
        </div>

        <div>
        {{ form_label(formulaire.title5,"Cinquième Titre (Optionnel)") }}
        {{ form_widget(formulaire.title5) }}
        </div>

        <div>
        {{ form_label(formulaire.Content5,"Paragraphe 05 (Optionnel)") }}
        {{ form_widget(formulaire.Content5) }}
        </div>

        <div>
        <button type="submit">Enregistrer</button>
        </div>

    {{ form_end(formulaire) }}


    </main>

{% endblock %}

templates/article_update.html.twig
{% extends "base.html.twig" %}

{% block content %}

    <main>

        <h2>Modification de mon article</h2>

    {{ form_start(formulaire) }}

        <div>
        {{ form_label(formulaire.title,"Titre") }}
        {{ form_widget(formulaire.title) }}
        </div>

        <div>
        {{ form_label(formulaire.content,"Paragraphe 01") }}
        {{ form_widget(formulaire.content) }}
        </div>

        <div>
        {{ form_label(formulaire.image,"Image 01 (Optionnel)") }}
        {{ form_widget(formulaire.image) }}
        </div>

        <div>
        {{ form_label(formulaire.title2,"Second Titre (Optionnel)") }}
        {{ form_widget(formulaire.title2) }}
        </div>

        <div>
        {{ form_label(formulaire.Content2,"Paragraphe 02") }}
        {{ form_widget(formulaire.Content2) }}
        </div>

        <div>
        {{ form_label(formulaire.image2,"Image 02") }}
        {{ form_widget(formulaire.image2) }}
        </div>

        <div>
        {{ form_label(formulaire.title3,"Troisième Titre (Optionnel)") }}
        {{ form_widget(formulaire.title3) }}
        </div>

        <div>
        {{ form_label(formulaire.Content3,"Paragraphe 03 (Optionnel)") }}
        {{ form_widget(formulaire.Content3) }}
        </div>

        <div>
        {{ form_label(formulaire.image3,"Image 03 (Optionnel)") }}
        {{ form_widget(formulaire.image3) }}
        </div>

        <div>
        {{ form_label(formulaire.title4,"Quatrième Titre (Optionnel)") }}
        {{ form_widget(formulaire.title4) }}
        </div>

        <div>
        {{ form_label(formulaire.Content4,"Paragraphe 04 (Optionnel)") }}
        {{ form_widget(formulaire.Content4) }}
        </div>

        <div>
        {{ form_label(formulaire.image4,"Image 04 (Optionnel)") }}
        {{ form_widget(formulaire.image4) }}
        </div>

        <div>
        {{ form_label(formulaire.title5,"Cinquième Titre (Optionnel)") }}
        {{ form_widget(formulaire.title5) }}
        </div>

        <div>
        {{ form_label(formulaire.Content5,"Paragraphe 05 (Optionnel)") }}
        {{ form_widget(formulaire.Content5) }}
        </div>

        <div>
        <button type="submit">Enregistrer</button>
        </div>

    {{ form_end(formulaire) }}


    </main>

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Ne3ko's Website{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
            <link rel="stylesheet" href="{{ asset('assets/css/reset.css') }}">
            <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
            <link rel="stylesheet" href="{{ asset('assets/css/menu_burger.css') }}">
            <link rel="stylesheet" href="{{ asset('assets/css/header.css') }}">
            <link rel="stylesheet" href="{{ asset('assets/css/footer.css') }}">
            <link rel="stylesheet" href="{{ asset('assets/css/body.css') }}">
            <link rel="stylesheet" href="{{ asset('assets/css/accueil.css') }}">
            
        {% endblock %}

        {% block javascripts %}
        <script src="{{ asset('assets/js/index.js') }}"></script>
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}
        {# Header #}
            <header id="header">
                <div class="right"><img src="{{ asset('assets/image/logo_Ne3ko.png') }}" alt="Ne3ko's face" width="400"></div>

                <div class="center" id="haut"><h1 class="h1">Welcome to Ne3ko's guide on New World !</h1></div>

                <div class="clear"></div>
            </header>

            {# Menu Burger #}
            <nav role="navigation">
                <div id="menuToggle">
                    <input type="checkbox" />

                    <span></span>
                    <span></span>
                    <span></span>

                    <ul id="menu">
                        <a href="{{ path('article_create') }}"><li>Ajouter un article</li></a>
                        <a href="#"><li>Espace Admin</li></a>
                        <a href="https://github.com/Ne3koo"><li>GitHub</li></a>
                        <a href="https://www.linkedin.com/in/julien-flament-a442b197/"><li>LinkedIn</li></a>
                    </ul>
                </div>
            </nav>

            {# Main #}
            {% block content %}{% endblock %}
            
            {# Retour en haut de page #}
            <div><a id="cRetour" class="cInvisible" href="#haut"></a></div>

            {# Footer #}
            <footer id="footer">

                <div class="center">
                    <h2 class="h1">Retrouvez mes réseaux GitHub et LinkedIn !</h2>
                </div>

                <div class="left">
                    <nav>
                        <ul class="flex">
                            <li id=""> <a href="https://github.com/Ne3koo"><img id="width" src="{{ asset('assets/image/github.png') }}" alt="Lien GitHub"><a href="https://github.com/Ne3koo"></a> </li>
                            <li id=""> <a href="https://www.linkedin.com/in/julien-flament-a442b197/"><img id="width2" src="{{ asset('assets/image/linkedin.png') }}" alt="Lien LinkedIn"></a> </li>
                        </ul>
                    </nav>
                </div>

                <div class="right">

                </div>

                <div class="clear"></div>
            </footer>
        {% endblock %}
    </body>
</html>